// Golden-game driver (phase P4). Shared by goldenGame.test.ts and
// `npm run golden:update` so the fixture and the assertion can never be
// generated by two different code paths.
//
// WHAT THIS IS, AND WHAT IT IS NOT
// --------------------------------
// This is a REGRESSION TRIPWIRE, not a correctness proof. The fixture is
// generated from today's engine, so it locks in today's behaviour — right or
// wrong. A green golden means "nothing changed", never "the rules are right".
// Judging correctness is the job of the hand-written waypoint assertions in
// goldenGame.test.ts, which name a specific rule and can be checked by a human
// against docs/game_mechanics_md.md. If you are reading this because the golden
// failed: find out WHICH rule moved before regenerating anything.
//
// The whole game is driven from one seed through the real deal/draw/discard
// cycle. Hardcoding cards would be simpler and would bypass the deck entirely
// — and the deck is where a card-conservation regression lives.

import type { BoardDef, Card, GameState, PlayerId, Program } from '../types';
import type { EventLog } from '../events';
import { createGame, executeTurn, isGameOver } from '../index';
import { theGauntlet } from '../boards';

/**
 * Fixed for all time: the fixture is meaningless if the deal can drift.
 *
 * This seed was CHOSEN, not picked at random. A seed is only worth freezing if
 * the game it deals actually exercises the rules — the first one tried ended on
 * turn 7 with everyone in a pit, having never fired a pusher, claimed a
 * checkpoint or ridden a belt. A golden like that passes while half the
 * rulebook rots. This one runs 18 turns to a real winner and fires every
 * mechanic the waypoint assertions below name.
 */
export const GOLDEN_SEED = 3393007;
export const GOLDEN_PLAYERS = ['Ada', 'Rex', 'Cy'];
/** Long enough for pits, respawns and checkpoints; short enough to read. */
export const GOLDEN_MAX_TURNS = 25;

export function goldenBoard(): BoardDef {
  // The Gauntlet carries pushers, gears, belts, lasers, pits and checkpoints —
  // a board with none of those would produce a golden that passes while half
  // the rulebook rots.
  return theGauntlet();
}

/**
 * The scripted policy. Deterministic and deliberately dumb: play the hand in
 * dealt order, leaving locked registers null.
 *
 * It is NOT trying to play well. It is trying to be a fixed function of the
 * hand, so that any change in the golden traces to the engine rather than to a
 * strategy that happened to react differently.
 */
export function programFor(state: GameState, player: PlayerId): Program {
  const robot = state.robots.find((r) => r.player === player)!;
  const hand = state.hands[player] ?? [];
  let next = 0;
  return robot.lockedRegisters.map((locked) =>
    locked ? null : (hand[next++] ?? null),
  ) as Program;
}

/** One robot's visible state — everything a rule can get wrong, nothing else. */
function snapshotRobots(state: GameState) {
  return state.robots.map((r) => ({
    player: r.player,
    x: r.pos.x,
    y: r.pos.y,
    facing: r.facing,
    damage: r.damage,
    lives: r.lives,
    checkpoints: r.checkpoints,
    destroyed: r.destroyed,
    eliminated: r.eliminated,
    /** Damage locks registers from 5 downward; repair releases them again. */
    lockedCount: r.lockedRegisters.filter((c) => c !== null).length,
  }));
}

/**
 * Total cards in the world. The board-game rule is one shared 84-card deck, so
 * this must hold at every turn boundary — a leak here is the kind of bug that
 * only shows up as a mysteriously short hand ten turns later.
 */
export function countCards(state: GameState): number {
  const inHands = Object.values(state.hands).reduce<number>((n, h) => n + h.length, 0);
  const locked = state.robots.reduce<number>(
    (n, r) => n + r.lockedRegisters.filter((c: Card | null) => c !== null).length,
    0,
  );
  return state.deck.drawPile.length + state.deck.discardPile.length + inHands + locked;
}

export interface GoldenTurn {
  turn: number;
  /** Full event log — the animation contract, so payload drift is caught too. */
  events: EventLog;
  robots: ReturnType<typeof snapshotRobots>;
  cardCount: number;
}

export interface GoldenGame {
  seed: number;
  board: string;
  players: string[];
  turns: GoldenTurn[];
  final: {
    turn: number;
    winner: string | null;
    over: boolean;
    robots: ReturnType<typeof snapshotRobots>;
  };
}

/** Play the scripted game. Same input every time, by construction. */
export function runGoldenGame(): GoldenGame {
  let state = createGame(goldenBoard(), GOLDEN_PLAYERS, GOLDEN_SEED);
  const turns: GoldenTurn[] = [];

  while (!isGameOver(state) && turns.length < GOLDEN_MAX_TURNS) {
    const turn = state.turn;
    const programs: Record<PlayerId, Program> = {};
    for (const robot of state.robots) {
      if (!robot.eliminated) programs[robot.player] = programFor(state, robot.player);
    }
    // Turn seed mirrors the hot-seat store's `initialSeed + turn`, so a golden
    // failure can be reproduced by starting a real game on GOLDEN_SEED.
    const result: { state: GameState; events: EventLog } = executeTurn(
      state,
      programs,
      GOLDEN_SEED + turn,
    );
    state = result.state;
    turns.push({
      turn,
      events: result.events,
      robots: snapshotRobots(state),
      cardCount: countCards(state),
    });
  }

  return {
    seed: GOLDEN_SEED,
    board: goldenBoard().name,
    players: [...GOLDEN_PLAYERS],
    turns,
    final: {
      turn: state.turn,
      winner: state.winner,
      over: isGameOver(state),
      robots: snapshotRobots(state),
    },
  };
}
